#!/bin/bash

#grep -rn --color=always --exclude=cscope.out --exclude=tags "$@" |
git grep -n --color=always "$@" |
  awk '{
         line=$0;
         ORS="";
         if (line ~/[a-z].?.?.?.?.?.?.?.?.?.?.?.?.?.?:.?.?.?.?.?.?.?.?.?.?.?.?.?.?[0-9]+.?.?.?.?.?.?.?.?.?.?.?.?.?.?:/)
         {
           n=split(line, a, ":");
           print("vim " a[1] " +" a[2] " ;# ");
           print(a[3]);
           for(i=4;i<n+1;i++){
             print(":" a[i])
           }
           print("\n");
         }
         else if (line ~/[a-z].?.?.?.?.?.?.?.?.?.?.?.?.?.?-.?.?.?.?.?.?.?.?.?.?.?.?.?.?[0-9]+.?.?.?.?.?.?.?.?.?.?.?.?.?.?-/)
         {
             n=split(line, a, "-");
             print("vim " a[1] " +" a[2] " ;# ");
             print(a[3]);
             for(i=4;i<n+1;i++){
               print(":" a[i])
             }
             print("\n");
         }
         else
         {
             print(line "\n");
         };
       }';
