#!/bin/bash

# GREP_COLORS
# Sets temporary grep colors to make a reasonably unabigous and fast regex match possible

# grep:
# -I     Process a binary file as if it did not contain matching data
# -r     Read  all  files under each directory, recursively, following symbolic links only if they are on the command line.  Note that if no file operand is given, grep searches the working directory.
# -n     Prefix each line of output with the 1-based line number within its input file.

# sed:
# -E     use extended regular expressions in the script
# The car crash-like regex is grouped like this
#   (start&sepcolor)(sep)(3numbercolor&number&sepcolor)sep
# ... where sep is : or -

GREP_COLORS="sl=:cx=:fn=35:ln=32:bn=32:se=36" grep -rn -I --color=always --exclude=cscope.out --exclude=tags "$@" |
  sed -E 's/(.*\[m\[K\[36m\[K)([:-])(\[m\[K\[32m\[K[0-9]+\[m\[K\[36m\[K)\2/vim \1 +\3 ;#/g'
