#!/bin/bash

# Sets temporary colors so that awk can match with an reasonably unabigous and fast regex

git -c color.grep.separator=cyan -c color.grep.linenumber=green grep -n --color=always "$@" |
  awk '{
         line=$0;
         ORS="";
         if (line ~/\033\[36m:\033\[m\033\[32m[0-9]+\033\[m\033\[36m:/)
         {
           n=split(line, a, ":");
           print("vim " a[1] " +" a[2] " ;# ");
           print(a[3]);
           for(i=4;i<n+1;i++){
             print(":" a[i])
           }
           print("\n");
         }
         else if (line ~/\033\[36m-\033\[m\033\[32m[0-9]+\033\[m\033\[36m-/)
         {
             n=split(line, a, "-");
             print("vim " a[1] " +" a[2] " ;# ");
             print(a[3]);
             for(i=4;i<n+1;i++){
               print("-" a[i])
             }
             print("\n");
         }
         else
         {
             print(line "\n");
         };
       }';
