#!/bin/bash

# git
# -c
# Sets temporary grep colors to make a reasonably unabigous and fast regex match possible

# git grep
# -n     Prefix the line number to matching lines.

# sed:
# -E     use extended regular expressions in the script
# The car crash-like regex is grouped like this
#   (start&sepcolor)(sep)(3numbercolor&number&sepcolor)sep
# ... where sep is : or -

git -c color.grep.separator=cyan -c color.grep.linenumber=green grep -n --color=always "$@" |
  sed -E 's/(.*\[36m)([:-])(\[m\[32m[0-9]+\[m\[36m)\2/vim \1 +\3 ;#/g'
